version: "3"

services:
  mariadb:  
    image: mariadb:10.10
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=fullstackphp
    ports:
      - 8011:3306
    volumes:
      - ./db_data:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8012:80
    environment:
      - PMA_ARBITRARY=1

  app:
    image: danielsobralnascimento/webserver:1.0
    volumes:
      - ./:/var/www/html
    ports:
      - 8010:80
    links:
      - mariadb
    depends_on:
      - mariadb
      - phpmyadmin
    tty: true